# Generated by Django 6.0.3 on 2026-04-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_preferido', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
    ]
