# Generated by Django 6.0.3 on 2026-04-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sesiones_dia_preferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones',
            name='dia_preferido',
            field=models.CharField(max_length=20),
        ),
    ]
