# Generated by Django 6.0.3 on 2026-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sesiones_dia_preferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sesiones',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sesiones',
            constraint=models.UniqueConstraint(fields=('nombre', 'telefono'), name='unique_sesion_cliente'),
        ),
    ]
