# Generated by Django 6.0.3 on 2026-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sesiones_fecha_solicitud_alter_sesiones_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiones',
            name='dia_sesion',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='horario_sesion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
