# Generated by Django 6.0.3 on 2026-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sesiones_dia_sesion_sesiones_horario_sesion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sesiones',
            name='unique_sesion_cliente',
        ),
        migrations.AddConstraint(
            model_name='sesiones',
            constraint=models.UniqueConstraint(fields=('nombre', 'telefono', 'dia_sesion'), name='unique_sesion_cliente'),
        ),
    ]
