# Generated by Django 6.0.3 on 2026-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosAutorizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios_autorizados',
            },
        ),
    ]
